pub use game_5::*;
/// This module was auto-generated with ethers-rs Abigen.
/// More information at: <https://github.com/gakonst/ethers-rs>
#[allow(
    clippy::enum_variant_names,
    clippy::too_many_arguments,
    clippy::upper_case_acronyms,
    clippy::type_complexity,
    dead_code,
    non_camel_case_types,
)]
pub mod game_5 {
    #[rustfmt::skip]
    const __ABI: &str = "[{\"inputs\":[{\"internalType\":\"address\",\"name\":\"winner\",\"type\":\"address\",\"components\":[],\"indexed\":false}],\"type\":\"event\",\"name\":\"Winner\",\"outputs\":[],\"anonymous\":false},{\"inputs\":[{\"internalType\":\"uint256\",\"name\":\"allowance\",\"type\":\"uint256\",\"components\":[]}],\"stateMutability\":\"nonpayable\",\"type\":\"function\",\"name\":\"giveMeAllowance\",\"outputs\":[]},{\"inputs\":[{\"internalType\":\"uint256\",\"name\":\"amount\",\"type\":\"uint256\",\"components\":[]}],\"stateMutability\":\"nonpayable\",\"type\":\"function\",\"name\":\"mint\",\"outputs\":[]},{\"inputs\":[],\"stateMutability\":\"nonpayable\",\"type\":\"function\",\"name\":\"win\",\"outputs\":[]}]";
    ///The parsed JSON ABI of the contract.
    pub static GAME5_ABI: ::ethers::contract::Lazy<::ethers::core::abi::Abi> = ::ethers::contract::Lazy::new(||
    ::ethers::core::utils::__serde_json::from_str(__ABI).expect("ABI is always valid"));
    #[rustfmt::skip]
    const __BYTECODE: &[u8] = &[
        96,
        128,
        96,
        64,
        82,
        52,
        128,
        21,
        97,
        0,
        16,
        87,
        96,
        0,
        128,
        253,
        91,
        80,
        97,
        1,
        196,
        128,
        97,
        0,
        32,
        96,
        0,
        57,
        96,
        0,
        243,
        254,
        96,
        128,
        96,
        64,
        82,
        52,
        128,
        21,
        97,
        0,
        16,
        87,
        96,
        0,
        128,
        253,
        91,
        80,
        96,
        4,
        54,
        16,
        97,
        0,
        65,
        87,
        96,
        0,
        53,
        96,
        224,
        28,
        128,
        99,
        71,
        60,
        169,
        108,
        20,
        97,
        0,
        70,
        87,
        128,
        99,
        160,
        113,
        45,
        104,
        20,
        97,
        0,
        80,
        87,
        128,
        99,
        177,
        155,
        51,
        35,
        20,
        97,
        0,
        99,
        87,
        91,
        96,
        0,
        128,
        253,
        91,
        97,
        0,
        78,
        97,
        0,
        118,
        86,
        91,
        0,
        91,
        97,
        0,
        78,
        97,
        0,
        94,
        54,
        96,
        4,
        97,
        1,
        51,
        86,
        91,
        97,
        0,
        201,
        86,
        91,
        97,
        0,
        78,
        97,
        0,
        113,
        54,
        96,
        4,
        97,
        1,
        51,
        86,
        91,
        97,
        1,
        20,
        86,
        91,
        51,
        96,
        0,
        144,
        129,
        82,
        96,
        32,
        129,
        144,
        82,
        96,
        64,
        144,
        32,
        84,
        97,
        39,
        16,
        17,
        21,
        97,
        0,
        148,
        87,
        96,
        0,
        128,
        253,
        91,
        96,
        64,
        81,
        51,
        129,
        82,
        127,
        116,
        92,
        144,
        182,
        86,
        180,
        170,
        254,
        41,
        108,
        140,
        163,
        90,
        234,
        207,
        229,
        108,
        185,
        108,
        144,
        225,
        211,
        32,
        229,
        218,
        100,
        63,
        255,
        16,
        81,
        182,
        192,
        144,
        96,
        32,
        1,
        96,
        64,
        81,
        128,
        145,
        3,
        144,
        161,
        86,
        91,
        51,
        96,
        0,
        144,
        129,
        82,
        96,
        1,
        96,
        32,
        82,
        96,
        64,
        129,
        32,
        128,
        84,
        131,
        146,
        144,
        97,
        0,
        232,
        144,
        132,
        144,
        97,
        1,
        98,
        86,
        91,
        144,
        145,
        85,
        80,
        80,
        51,
        96,
        0,
        144,
        129,
        82,
        96,
        32,
        129,
        144,
        82,
        96,
        64,
        129,
        32,
        128,
        84,
        131,
        146,
        144,
        97,
        1,
        12,
        144,
        132,
        144,
        97,
        1,
        123,
        86,
        91,
        144,
        145,
        85,
        80,
        80,
        80,
        86,
        91,
        51,
        96,
        0,
        144,
        129,
        82,
        96,
        1,
        96,
        32,
        82,
        96,
        64,
        129,
        32,
        128,
        84,
        131,
        146,
        144,
        97,
        1,
        12,
        144,
        132,
        144,
        97,
        1,
        123,
        86,
        91,
        96,
        0,
        96,
        32,
        130,
        132,
        3,
        18,
        21,
        97,
        1,
        69,
        87,
        96,
        0,
        128,
        253,
        91,
        80,
        53,
        145,
        144,
        80,
        86,
        91,
        99,
        78,
        72,
        123,
        113,
        96,
        224,
        27,
        96,
        0,
        82,
        96,
        17,
        96,
        4,
        82,
        96,
        36,
        96,
        0,
        253,
        91,
        129,
        129,
        3,
        129,
        129,
        17,
        21,
        97,
        1,
        117,
        87,
        97,
        1,
        117,
        97,
        1,
        76,
        86,
        91,
        146,
        145,
        80,
        80,
        86,
        91,
        128,
        130,
        1,
        128,
        130,
        17,
        21,
        97,
        1,
        117,
        87,
        97,
        1,
        117,
        97,
        1,
        76,
        86,
        254,
        162,
        100,
        105,
        112,
        102,
        115,
        88,
        34,
        18,
        32,
        192,
        255,
        65,
        146,
        58,
        121,
        10,
        156,
        144,
        175,
        22,
        48,
        187,
        12,
        218,
        69,
        133,
        60,
        116,
        88,
        248,
        22,
        227,
        110,
        165,
        164,
        242,
        246,
        97,
        166,
        78,
        63,
        100,
        115,
        111,
        108,
        99,
        67,
        0,
        8,
        19,
        0,
        51,
    ];
    ///The bytecode of the contract.
    pub static GAME5_BYTECODE: ::ethers::core::types::Bytes = ::ethers::core::types::Bytes::from_static(
        __BYTECODE,
    );
    #[rustfmt::skip]
    const __DEPLOYED_BYTECODE: &[u8] = &[
        96,
        128,
        96,
        64,
        82,
        52,
        128,
        21,
        97,
        0,
        16,
        87,
        96,
        0,
        128,
        253,
        91,
        80,
        96,
        4,
        54,
        16,
        97,
        0,
        65,
        87,
        96,
        0,
        53,
        96,
        224,
        28,
        128,
        99,
        71,
        60,
        169,
        108,
        20,
        97,
        0,
        70,
        87,
        128,
        99,
        160,
        113,
        45,
        104,
        20,
        97,
        0,
        80,
        87,
        128,
        99,
        177,
        155,
        51,
        35,
        20,
        97,
        0,
        99,
        87,
        91,
        96,
        0,
        128,
        253,
        91,
        97,
        0,
        78,
        97,
        0,
        118,
        86,
        91,
        0,
        91,
        97,
        0,
        78,
        97,
        0,
        94,
        54,
        96,
        4,
        97,
        1,
        51,
        86,
        91,
        97,
        0,
        201,
        86,
        91,
        97,
        0,
        78,
        97,
        0,
        113,
        54,
        96,
        4,
        97,
        1,
        51,
        86,
        91,
        97,
        1,
        20,
        86,
        91,
        51,
        96,
        0,
        144,
        129,
        82,
        96,
        32,
        129,
        144,
        82,
        96,
        64,
        144,
        32,
        84,
        97,
        39,
        16,
        17,
        21,
        97,
        0,
        148,
        87,
        96,
        0,
        128,
        253,
        91,
        96,
        64,
        81,
        51,
        129,
        82,
        127,
        116,
        92,
        144,
        182,
        86,
        180,
        170,
        254,
        41,
        108,
        140,
        163,
        90,
        234,
        207,
        229,
        108,
        185,
        108,
        144,
        225,
        211,
        32,
        229,
        218,
        100,
        63,
        255,
        16,
        81,
        182,
        192,
        144,
        96,
        32,
        1,
        96,
        64,
        81,
        128,
        145,
        3,
        144,
        161,
        86,
        91,
        51,
        96,
        0,
        144,
        129,
        82,
        96,
        1,
        96,
        32,
        82,
        96,
        64,
        129,
        32,
        128,
        84,
        131,
        146,
        144,
        97,
        0,
        232,
        144,
        132,
        144,
        97,
        1,
        98,
        86,
        91,
        144,
        145,
        85,
        80,
        80,
        51,
        96,
        0,
        144,
        129,
        82,
        96,
        32,
        129,
        144,
        82,
        96,
        64,
        129,
        32,
        128,
        84,
        131,
        146,
        144,
        97,
        1,
        12,
        144,
        132,
        144,
        97,
        1,
        123,
        86,
        91,
        144,
        145,
        85,
        80,
        80,
        80,
        86,
        91,
        51,
        96,
        0,
        144,
        129,
        82,
        96,
        1,
        96,
        32,
        82,
        96,
        64,
        129,
        32,
        128,
        84,
        131,
        146,
        144,
        97,
        1,
        12,
        144,
        132,
        144,
        97,
        1,
        123,
        86,
        91,
        96,
        0,
        96,
        32,
        130,
        132,
        3,
        18,
        21,
        97,
        1,
        69,
        87,
        96,
        0,
        128,
        253,
        91,
        80,
        53,
        145,
        144,
        80,
        86,
        91,
        99,
        78,
        72,
        123,
        113,
        96,
        224,
        27,
        96,
        0,
        82,
        96,
        17,
        96,
        4,
        82,
        96,
        36,
        96,
        0,
        253,
        91,
        129,
        129,
        3,
        129,
        129,
        17,
        21,
        97,
        1,
        117,
        87,
        97,
        1,
        117,
        97,
        1,
        76,
        86,
        91,
        146,
        145,
        80,
        80,
        86,
        91,
        128,
        130,
        1,
        128,
        130,
        17,
        21,
        97,
        1,
        117,
        87,
        97,
        1,
        117,
        97,
        1,
        76,
        86,
        254,
        162,
        100,
        105,
        112,
        102,
        115,
        88,
        34,
        18,
        32,
        192,
        255,
        65,
        146,
        58,
        121,
        10,
        156,
        144,
        175,
        22,
        48,
        187,
        12,
        218,
        69,
        133,
        60,
        116,
        88,
        248,
        22,
        227,
        110,
        165,
        164,
        242,
        246,
        97,
        166,
        78,
        63,
        100,
        115,
        111,
        108,
        99,
        67,
        0,
        8,
        19,
        0,
        51,
    ];
    ///The deployed bytecode of the contract.
    pub static GAME5_DEPLOYED_BYTECODE: ::ethers::core::types::Bytes = ::ethers::core::types::Bytes::from_static(
        __DEPLOYED_BYTECODE,
    );
    pub struct Game5<M>(::ethers::contract::Contract<M>);
    impl<M> ::core::clone::Clone for Game5<M> {
        fn clone(&self) -> Self {
            Self(::core::clone::Clone::clone(&self.0))
        }
    }
    impl<M> ::core::ops::Deref for Game5<M> {
        type Target = ::ethers::contract::Contract<M>;
        fn deref(&self) -> &Self::Target {
            &self.0
        }
    }
    impl<M> ::core::ops::DerefMut for Game5<M> {
        fn deref_mut(&mut self) -> &mut Self::Target {
            &mut self.0
        }
    }
    impl<M> ::core::fmt::Debug for Game5<M> {
        fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
            f.debug_tuple(stringify!(Game5)).field(&self.address()).finish()
        }
    }
    impl<M: ::ethers::providers::Middleware> Game5<M> {
        /// Creates a new contract instance with the specified `ethers` client at
        /// `address`. The contract derefs to a `ethers::Contract` object.
        pub fn new<T: Into<::ethers::core::types::Address>>(
            address: T,
            client: ::std::sync::Arc<M>,
        ) -> Self {
            Self(
                ::ethers::contract::Contract::new(
                    address.into(),
                    GAME5_ABI.clone(),
                    client,
                ),
            )
        }
        /// Constructs the general purpose `Deployer` instance based on the provided constructor arguments and sends it.
        /// Returns a new instance of a deployer that returns an instance of this contract after sending the transaction
        ///
        /// Notes:
        /// - If there are no constructor arguments, you should pass `()` as the argument.
        /// - The default poll duration is 7 seconds.
        /// - The default number of confirmations is 1 block.
        ///
        ///
        /// # Example
        ///
        /// Generate contract bindings with `abigen!` and deploy a new contract instance.
        ///
        /// *Note*: this requires a `bytecode` and `abi` object in the `greeter.json` artifact.
        ///
        /// ```ignore
        /// # async fn deploy<M: ethers::providers::Middleware>(client: ::std::sync::Arc<M>) {
        ///     abigen!(Greeter, "../greeter.json");
        ///
        ///    let greeter_contract = Greeter::deploy(client, "Hello world!".to_string()).unwrap().send().await.unwrap();
        ///    let msg = greeter_contract.greet().call().await.unwrap();
        /// # }
        /// ```
        pub fn deploy<T: ::ethers::core::abi::Tokenize>(
            client: ::std::sync::Arc<M>,
            constructor_args: T,
        ) -> ::core::result::Result<
            ::ethers::contract::builders::ContractDeployer<M, Self>,
            ::ethers::contract::ContractError<M>,
        > {
            let factory = ::ethers::contract::ContractFactory::new(
                GAME5_ABI.clone(),
                GAME5_BYTECODE.clone().into(),
                client,
            );
            let deployer = factory.deploy(constructor_args)?;
            let deployer = ::ethers::contract::ContractDeployer::new(deployer);
            Ok(deployer)
        }
        ///Calls the contract's `giveMeAllowance` (0xb19b3323) function
        pub fn give_me_allowance(
            &self,
            allowance: ::ethers::core::types::U256,
        ) -> ::ethers::contract::builders::ContractCall<M, ()> {
            self.0
                .method_hash([177, 155, 51, 35], allowance)
                .expect("method not found (this should never happen)")
        }
        ///Calls the contract's `mint` (0xa0712d68) function
        pub fn mint(
            &self,
            amount: ::ethers::core::types::U256,
        ) -> ::ethers::contract::builders::ContractCall<M, ()> {
            self.0
                .method_hash([160, 113, 45, 104], amount)
                .expect("method not found (this should never happen)")
        }
        ///Calls the contract's `win` (0x473ca96c) function
        pub fn win(&self) -> ::ethers::contract::builders::ContractCall<M, ()> {
            self.0
                .method_hash([71, 60, 169, 108], ())
                .expect("method not found (this should never happen)")
        }
        ///Gets the contract's `Winner` event
        pub fn winner_filter(
            &self,
        ) -> ::ethers::contract::builders::Event<::std::sync::Arc<M>, M, WinnerFilter> {
            self.0.event()
        }
        /// Returns an `Event` builder for all the events of this contract.
        pub fn events(
            &self,
        ) -> ::ethers::contract::builders::Event<::std::sync::Arc<M>, M, WinnerFilter> {
            self.0.event_with_filter(::core::default::Default::default())
        }
    }
    impl<M: ::ethers::providers::Middleware> From<::ethers::contract::Contract<M>>
    for Game5<M> {
        fn from(contract: ::ethers::contract::Contract<M>) -> Self {
            Self::new(contract.address(), contract.client())
        }
    }
    #[derive(
        Clone,
        ::ethers::contract::EthEvent,
        ::ethers::contract::EthDisplay,
        Default,
        Debug,
        PartialEq,
        Eq,
        Hash
    )]
    #[ethevent(name = "Winner", abi = "Winner(address)")]
    pub struct WinnerFilter {
        pub winner: ::ethers::core::types::Address,
    }
    ///Container type for all input parameters for the `giveMeAllowance` function with signature `giveMeAllowance(uint256)` and selector `0xb19b3323`
    #[derive(
        Clone,
        ::ethers::contract::EthCall,
        ::ethers::contract::EthDisplay,
        Default,
        Debug,
        PartialEq,
        Eq,
        Hash
    )]
    #[ethcall(name = "giveMeAllowance", abi = "giveMeAllowance(uint256)")]
    pub struct GiveMeAllowanceCall {
        pub allowance: ::ethers::core::types::U256,
    }
    ///Container type for all input parameters for the `mint` function with signature `mint(uint256)` and selector `0xa0712d68`
    #[derive(
        Clone,
        ::ethers::contract::EthCall,
        ::ethers::contract::EthDisplay,
        Default,
        Debug,
        PartialEq,
        Eq,
        Hash
    )]
    #[ethcall(name = "mint", abi = "mint(uint256)")]
    pub struct MintCall {
        pub amount: ::ethers::core::types::U256,
    }
    ///Container type for all input parameters for the `win` function with signature `win()` and selector `0x473ca96c`
    #[derive(
        Clone,
        ::ethers::contract::EthCall,
        ::ethers::contract::EthDisplay,
        Default,
        Debug,
        PartialEq,
        Eq,
        Hash
    )]
    #[ethcall(name = "win", abi = "win()")]
    pub struct WinCall;
    ///Container type for all of the contract's call
    #[derive(Clone, ::ethers::contract::EthAbiType, Debug, PartialEq, Eq, Hash)]
    pub enum Game5Calls {
        GiveMeAllowance(GiveMeAllowanceCall),
        Mint(MintCall),
        Win(WinCall),
    }
    impl ::ethers::core::abi::AbiDecode for Game5Calls {
        fn decode(
            data: impl AsRef<[u8]>,
        ) -> ::core::result::Result<Self, ::ethers::core::abi::AbiError> {
            let data = data.as_ref();
            if let Ok(decoded)
                = <GiveMeAllowanceCall as ::ethers::core::abi::AbiDecode>::decode(data) {
                return Ok(Self::GiveMeAllowance(decoded));
            }
            if let Ok(decoded)
                = <MintCall as ::ethers::core::abi::AbiDecode>::decode(data) {
                return Ok(Self::Mint(decoded));
            }
            if let Ok(decoded)
                = <WinCall as ::ethers::core::abi::AbiDecode>::decode(data) {
                return Ok(Self::Win(decoded));
            }
            Err(::ethers::core::abi::Error::InvalidData.into())
        }
    }
    impl ::ethers::core::abi::AbiEncode for Game5Calls {
        fn encode(self) -> Vec<u8> {
            match self {
                Self::GiveMeAllowance(element) => {
                    ::ethers::core::abi::AbiEncode::encode(element)
                }
                Self::Mint(element) => ::ethers::core::abi::AbiEncode::encode(element),
                Self::Win(element) => ::ethers::core::abi::AbiEncode::encode(element),
            }
        }
    }
    impl ::core::fmt::Display for Game5Calls {
        fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
            match self {
                Self::GiveMeAllowance(element) => ::core::fmt::Display::fmt(element, f),
                Self::Mint(element) => ::core::fmt::Display::fmt(element, f),
                Self::Win(element) => ::core::fmt::Display::fmt(element, f),
            }
        }
    }
    impl ::core::convert::From<GiveMeAllowanceCall> for Game5Calls {
        fn from(value: GiveMeAllowanceCall) -> Self {
            Self::GiveMeAllowance(value)
        }
    }
    impl ::core::convert::From<MintCall> for Game5Calls {
        fn from(value: MintCall) -> Self {
            Self::Mint(value)
        }
    }
    impl ::core::convert::From<WinCall> for Game5Calls {
        fn from(value: WinCall) -> Self {
            Self::Win(value)
        }
    }
}
